apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nuusm0lep-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/nuusm0lep-java-quarkus-gitops